### ISSUE TITLE
echem_read fails to find start of data in regular CV file

### ISSUE THREAD

**Issue by asgerha** [SPOMAN/osctools#4]
[ss6701.txt](https://github.com/SPOMAN/osctools/files/1422136/ss6701.txt)

The following script fails to load the cv file with the following error: "Error in find_data(file, n_init = n_init * 2) :  Start of data not found anywhere in the file."

```
library(tidyverse)
library(osctools)
file <- ("ss6701.txt")
data1 <- echem_read(file)
```

After some discussion with other users, i realize there may be a difference between the file format outputted by the different potentiostats in the lab, and that this might cause the error?

**Comment by emiltb** [comment]
There is definitely differences between the potentiostats - I thought I already did take most of the weird cases into account with the current implementation of `find_data()`, but that is clearly not the case.

Thanks for submitting this. I will take a look at it soon.

**Comment by asgerha** [comment]
Great! I'm looking forward to using the package!

2017-10-28 15:42 GMT+02:00 Emil Bjerglund Pedersen <notifications@github.com
