### ISSUE TITLE
Loading CV files

### ISSUE THREAD

**Issue by asgerha** [SPOMAN/osctools#5]
Upon using echem_read on the attached file i get the error: 
"Error in find_data(file, n_init = n_init * 2) : 
  Start of data not found anywhere in the file."
[GC7 DB3 cv4 weird.txt](https://github.com/SPOMAN/osctools/files/1833739/GC7.DB3.cv4.weird.txt)

**Comment by emiltb** [comment]
I cannot reproduce the problem on my system - it reads the file just fine:

    > echem_read("C:/Users/emilbp/Downloads/GC7.DB3.cv4.weird.txt")
    Cyclic Voltammetry at 0.1 V/s
    Initial scan polarity: N, Scan segments: 2
    Init E: 0 V, High E: 0 V, Low E: -1.6 V
    Sensitivity: 2e-06, Quiet time: 2 s
    
    # A tibble: 3,199 x 6
    potential       current direc change sweep    cv
    <dbl>         <dbl> <chr>  <dbl> <dbl> <dbl>
      1  -0.00100 -0.0000000287 neg       0.    1.    1.
    2  -0.00200 -0.0000000324 neg       0.    1.    1.
    3  -0.00300 -0.0000000363 neg       0.    1.    1.
    4  -0.00400 -0.0000000363 neg       0.    1.    1.
    5  -0.00500 -0.0000000356 neg       0.    1.    1.
    # ... with 3,194 more rows

Does it help if you install the latest version of the package with `devtools::install_github('spoman/osctools', force = TRUE)`
